// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpdmouaegymycoycuwxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwZG1vdWFlZ3lteWNveWN1d3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTgyMDksImV4cCI6MjA2NjgzNDIwOX0.VXBuIJ6ugL1_qDTv7xvjgYwf1unS8X-cW7W1h2NN8iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});